// Code generated by goctl. DO NOT EDIT.
// Source: block.proto

package server

import (
	"context"

	"block/block"
	"block/internal/logic"
	"block/internal/svc"
)

type BlockServer struct {
	svcCtx *svc.ServiceContext
	block.UnimplementedBlockServer
}

func NewBlockServer(svcCtx *svc.ServiceContext) *BlockServer {
	return &BlockServer{
		svcCtx: svcCtx,
	}
}

func (s *BlockServer) Ping(ctx context.Context, in *block.Request) (*block.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
