// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bargainFieldNames          = builder.RawFieldNames(&Bargain{})
	bargainRows                = strings.Join(bargainFieldNames, ",")
	bargainRowsExpectAutoSet   = strings.Join(stringx.Remove(bargainFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bargainRowsWithPlaceHolder = strings.Join(stringx.Remove(bargainFieldNames, "`bargain_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	bargainModel interface {
		Insert(ctx context.Context, data *Bargain) (sql.Result, error)
		FindOne(ctx context.Context, bargainId int64) (*Bargain, error)
		FindOneById(ctx context.Context, id int64) (*Bargain, error)
		Update(ctx context.Context, data *Bargain) error
		Delete(ctx context.Context, bargainId int64) error
		FindBargainByUserId(ctx context.Context, userId int64,cryptominerTypeid int64) (*Bargain, error)
		FindBargainByCryptominerId(ctx context.Context, userId int64,cryptominerId int64) (*Bargain, error)
		FindBargainForRule(ctx context.Context, userId int64) (*Bargain, error)
		FindBargainRecord(ctx context.Context, userId int64,bargainId int64) (*Bargain, error)
	}

	defaultBargainModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Bargain struct {
		BargainId         int64        `db:"bargain_id"`
		Id                int64        `db:"id"`
		UserId            int64        `db:"user_id"`
		CryptominerId     int64        `db:"cryptominer_id"`
		CryptominerTypeid int64        `db:"cryptominer_typeid"`
		CryptominerPrice  int64        `db:"cryptominer_price"`
		RemainingPrice    float64      `db:"remaining_price"`
		ActivityStartTime time.Time    `db:"activity_start_time"`
		ActivityEndTime   sql.NullTime `db:"activity_end_time"`
		UnusedData        string       `db:"unused_data"`
		UsedData          string       `db:"used_data"`
	}
)

func newBargainModel(conn sqlx.SqlConn) *defaultBargainModel {
	return &defaultBargainModel{
		conn:  conn,
		table: "`bargain`",
	}
}

func (m *defaultBargainModel) Delete(ctx context.Context, bargainId int64) error {
	query := fmt.Sprintf("delete from %s where `bargain_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, bargainId)
	return err
}

func (m *defaultBargainModel) FindOne(ctx context.Context, bargainId int64) (*Bargain, error) {
	query := fmt.Sprintf("select %s from %s where `bargain_id` = ? limit 1", bargainRows, m.table)
	var resp Bargain
	err := m.conn.QueryRowCtx(ctx, &resp, query, bargainId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBargainModel) FindOneById(ctx context.Context, id int64) (*Bargain, error) {
	var resp Bargain
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bargainRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBargainModel) Insert(ctx context.Context, data *Bargain) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, bargainRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BargainId, data.Id, data.UserId, data.CryptominerId, data.CryptominerTypeid, data.CryptominerPrice, data.RemainingPrice, data.ActivityStartTime, data.ActivityEndTime, data.UnusedData, data.UsedData)
	return ret, err
}

func (m *defaultBargainModel) Update(ctx context.Context, newData *Bargain) error {
	query := fmt.Sprintf("update %s set %s where `bargain_id` = ?", m.table, bargainRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.CryptominerId, newData.CryptominerTypeid, newData.CryptominerPrice, newData.RemainingPrice, newData.ActivityStartTime, newData.ActivityEndTime, newData.UnusedData, newData.UsedData, newData.BargainId)
	return err
}

func (m *defaultBargainModel) FindBargainByUserId(ctx context.Context, userId int64,cryptominerId int64) (*Bargain, error) {
	var resp Bargain
	today := time.Now().Format("2006-01-02")+"%"
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `cryptominer_typeid` = ?  and DATE(`activity_start_time`) like ? limit 1", bargainRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, cryptominerId, today)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBargainModel) FindBargainByCryptominerId(ctx context.Context, userId int64,cryptominerId int64) (*Bargain, error) {
	var resp Bargain
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `cryptominer_id` = ? limit 1", bargainRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, cryptominerId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBargainModel) FindBargainForRule(ctx context.Context, userId int64) (*Bargain, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", bargainRows, m.table)
	var resp Bargain
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBargainModel) FindBargainRecord(ctx context.Context, userId int64,bargainId int64) (*Bargain, error) {
	var resp Bargain
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `bargain_id` = ? limit 1", bargainRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, bargainId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBargainModel) tableName() string {
	return m.table
}
