// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	purchaseRecordsFieldNames          = builder.RawFieldNames(&PurchaseRecords{})
	purchaseRecordsRows                = strings.Join(purchaseRecordsFieldNames, ",")
	purchaseRecordsRowsExpectAutoSet   = strings.Join(stringx.Remove(purchaseRecordsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	purchaseRecordsRowsWithPlaceHolder = strings.Join(stringx.Remove(purchaseRecordsFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	purchaseRecordsModel interface {
		Insert(ctx context.Context, data *PurchaseRecords) (sql.Result, error)
		FindOne(ctx context.Context, userId int64) (*PurchaseRecords, error)
		FindAllPurchaseRecord(ctx context.Context, userId int64) ([]*PurchaseRecords, error)
		FindOneByPurchaseRecordId(ctx context.Context, purchaseRecordId int64) (*PurchaseRecords, error)
		Update(ctx context.Context, data *PurchaseRecords) error
		Delete(ctx context.Context, userId int64) error
		JudgeGoodsPurchase(ctx context.Context, userId int64, goodName string) (*PurchaseRecords, error)
		JudgeGoodsPurchaseForBargain(ctx context.Context, userId int64, goodName string) (*PurchaseRecords, error)
	}

	defaultPurchaseRecordsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PurchaseRecords struct {
		UserId           int64          `db:"user_id"`
		PurchaseRecordId int64          `db:"purchase_record_id"`
		CreatedAt        time.Time      `db:"created_at"`
		UpdatedAt        sql.NullTime   `db:"updated_at"`
		DeletedAt        sql.NullTime   `db:"deleted_at"`
		GoodName         string         `db:"good_name"`
		GoodPicture      sql.NullString `db:"good_picture"`
		PurchaseWay      string         `db:"purchase_way"`
		GoodQuantity     int64          `db:"good_quantity"`
		PurchaseTime     time.Time      `db:"purchase_time"`
		PurchasePrice    sql.NullFloat64  `db:"purchase_price"`
		PaymentWay       string     	`db:"payment_way"`
	}
)

func newPurchaseRecordsModel(conn sqlx.SqlConn) *defaultPurchaseRecordsModel {
	return &defaultPurchaseRecordsModel{
		conn:  conn,
		table: "`purchase_records`",
	}
}

func (m *defaultPurchaseRecordsModel) Delete(ctx context.Context, userId int64) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultPurchaseRecordsModel) FindOne(ctx context.Context, userId int64) (*PurchaseRecords, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", purchaseRecordsRows, m.table)
	var resp PurchaseRecords
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPurchaseRecordsModel) FindAllPurchaseRecord(ctx context.Context, userId int64) ([]*PurchaseRecords, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? ", purchaseRecordsRows, m.table)
	var resp []*PurchaseRecords
	err := m.conn.QueryRowsCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPurchaseRecordsModel) FindOneByPurchaseRecordId(ctx context.Context, purchaseRecordId int64) (*PurchaseRecords, error) {
	var resp PurchaseRecords
	query := fmt.Sprintf("select %s from %s where `purchase_record_id` = ? limit 1", purchaseRecordsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, purchaseRecordId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPurchaseRecordsModel) Insert(ctx context.Context, data *PurchaseRecords) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, purchaseRecordsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.PurchaseRecordId, data.DeletedAt, data.GoodName, data.GoodPicture, data.PurchaseWay, data.GoodQuantity, data.PurchaseTime, data.PurchasePrice, data.PaymentWay)
	return ret, err
}

func (m *defaultPurchaseRecordsModel) Update(ctx context.Context, newData *PurchaseRecords) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, purchaseRecordsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.PurchaseRecordId, newData.DeletedAt, newData.GoodName, newData.GoodPicture, newData.PurchaseWay, newData.GoodQuantity, newData.PurchaseTime, newData.PurchasePrice, newData.PaymentWay, newData.UserId)
	return err
}

func (m *defaultPurchaseRecordsModel) JudgeGoodsPurchase (ctx context.Context, userId int64,goodName string) (*PurchaseRecords, error) {
	var resp PurchaseRecords
	today := time.Now().Format("2006-01-02")+"%"
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `good_name` = ? and DATE(`purchase_time`) like ? limit 1", purchaseRecordsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, goodName, today)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPurchaseRecordsModel) JudgeGoodsPurchaseForBargain (ctx context.Context, userId int64,goodName string) (*PurchaseRecords, error) {
	var resp PurchaseRecords
	today := time.Now().Format("2006-01-02")+"%"
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `good_name` = ? and `purchase_way` = ? and DATE(`purchase_time`) like ? limit 1", purchaseRecordsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, goodName,"1", today)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPurchaseRecordsModel) tableName() string {
	return m.table
}


